In [ ]:
import importlib
import json
import pandas as pd
utils = importlib.import_module("eval-app.codes.utils")

d_providers = {
    'GPT-4o': 'GPT-4o',
    'Claude 3.7 Sonnet': 'Claude 3.7 Sonnet',
    'Gemini 2.5 Pro': 'Gemini 2.5 Pro',
    'Gemini 2.5 Flash': 'Gemini 2.5 Flash',
    'Llama 3.3 90B': 'Llama 3.3 90B',
    'Mistral Large 2': 'Mistral Large 2',
    'Toxpipe (RAG) [GPT-4o]': 'GPT-4o',
    'Toxpipe (RAG) [Claude-3.7 Sonnet]': 'Claude 3.5 Sonnet',
    'Toxpipe (RAG) [Gemini 2.5 Pro]': 'Gemini 2.5 Pro',
    'Toxpipe (RAG) [Gemini 2.5 Flash]': 'Gemini 2.5 Flash',
    'Toxpipe (RAG) [Llama 3.3 90B]': 'Llama 3.3 90B',
    'Toxpipe (RAG) [Mistral Large 2]': 'Mistral Large 2',
    'Toxpipe (Agentic) [GPT-4o]': 'GPT-4o'
}

for prompt_type in ['abt-qa-assertion-prompts_mixed', 'tox-type-assertion-prompts_human', 'tox-type-assertion-prompts_rat']:

    df = pd.DataFrame(columns=['provider', 'prompt']).set_index(['provider', 'prompt'])

    for level in ['base-model', 'rag']:

        eval_name = f'{level}_{prompt_type}'

        df_eval = pd.DataFrame()

        for f in (utils.Config.DIR_TEST / eval_name / 'output').glob('output_*.json'):
            with open(f) as fp:
                d = json.load(fp)

            r = {}
            for t in d['tests']:
                level_accessed = 'base'
                if level == 'rag' and t['response']['steps_taken'][-1] == 'query_with_context':
                    level_accessed = 'rag'

                result =  'no-assertion' if not t['response']['results'] else 'pass' if t['response']['results']['pass'] else 'fail'

                r[f'provider'] = r.get(f'provider', []) + [d_providers[t['provider']['label']]]
                r[f'prompt'] = r.get(f'prompt', []) + [t['prompt'].format(**t['vars'])]
                r[f'level_{level}'] = r.get(f'level_{level}', []) + [level_accessed]
                r[f'result_{level}'] = r.get(f'result_{level}', []) + [result]

            df_eval = pd.concat([df_eval, pd.DataFrame(r)], axis=0).reset_index(drop=True)
    
        df = df.join(df_eval.set_index(['provider', 'prompt']), how='outer')

    rag_success = df[(df['result_base-model'] == 'fail') & (df['level_rag'] == 'rag') & (df['result_rag'] == 'pass')].reset_index()

    display(rag_success)
    print(rag_success['prompt'].values)

    rag_success['prompt']
    print(len(rag_success))

Empty DataFrame
Columns: [provider, prompt, level_base-model, result_base-model, level_rag, result_rag]
Index: []

[]
0

,provider,prompt,level_base-model,result_base-model,level_rag,result_rag
0,Claude 3.5 Sonnet,Answer the following question with a list of s...,base,fail,rag,pass
1,Claude 3.5 Sonnet,Answer the following question with a list of s...,base,fail,rag,pass
2,Claude 3.5 Sonnet,Answer the following question with a list of s...,base,fail,rag,pass
3,Claude 3.5 Sonnet,Answer the following question with a list of s...,base,fail,rag,pass
4,GPT-4o,Answer the following question with a list of s...,base,fail,rag,pass
5,GPT-4o,Answer the following question with a list of s...,base,fail,rag,pass
6,GPT-4o,Answer the following question with a list of s...,base,fail,rag,pass
7,Gemini 1.5 Pro,Answer the following question with a list of s...,base,fail,rag,pass
8,Gemini 1.5 Pro,Answer the following question with a list of s...,base,fail,rag,pass
9,Gemini 1.5 Pro,Answer the following question with a list of s...,base,fail,rag,pass
10,Gemini 1.5 Pro,Answer the following question with a list of s...,base,fail,rag,pass
11,Mistral Large 2,Answer the following question with a list of s...,base,fail,rag,pass

['Answer the following question with a list of string. List the Musculoskeletal system toxicity of Atorvastatin or its synonyms with CAS number 134523-00-5 on human'
 'Answer the following question with a list of string. List the Nervous system/Neurological toxicity of Benzene or its synonyms with CAS number 71-43-2 on human'
 'Answer the following question with a list of string. List the Nervous system/Neurological toxicity of Methylmercury or its synonyms with CAS number 16056-34-1 on human'
 'Answer the following question with a list of string. List the Sub acute toxicity of Methylmercury or its synonyms with CAS number 16056-34-1 on human'
 'Answer the following question with a list of string. List the Nervous system/Neurological toxicity of Methylmercury or its synonyms with CAS number 16056-34-1 on human'
 'Answer the following question with a list of string. List the Respiratory system toxicity of Benzene or its synonyms with CAS number 71-43-2 on human'
 'Answer the following question with a list of string. List the Sub acute toxicity of Methylmercury or its synonyms with CAS number 16056-34-1 on human'
 'Answer the following question with a list of string. List the Chronic toxicity of Vinylchloride or its synonyms with CAS number 75-01-4 on human'
 'Answer the following question with a list of string. List the Endocrine system toxicity of Prednisone or its synonyms with CAS number 53-03-2 on human'
 'Answer the following question with a list of string. List the Musculoskeletal system toxicity of Atorvastatin or its synonyms with CAS number 134523-00-5 on human'
 'Answer the following question with a list of string. List the Nervous system/Neurological toxicity of Methylmercury or its synonyms with CAS number 16056-34-1 on human'
 'Answer the following question with a list of string. List the Musculoskeletal system toxicity of Atorvastatin or its synonyms with CAS number 134523-00-5 on human']
12

Empty DataFrame
Columns: [provider, prompt, level_base-model, result_base-model, level_rag, result_rag]
Index: []

[]
0

In [13]:
t

{'provider': {'config': {'max_iterations': 10,
   'model': 'claude-3-5-sonnet',
   'summarize': 'false',
   'temp': 0},
  'id': 'rag',
  'label': 'Toxpipe (RAG) [Claude-3.5 Sonnet]'},
 'prompt': 'Answer the following question with a list of string. List the {effect_type} of {chem_casrn} on rat',
 'vars': {'chem_casrn': '6-Methyl-2,5-diphenyl-6H-1,3,4-thiadiazine or its synonyms with CAS number 62625-70-1',
  'effect_type': 'Toxicokinetic parameters'},
 'assert': {},
 'response': {'output': "Based on the provided resources, here is a list of toxicokinetic parameters of 6-Methyl-2,5-diphenyl-6H-1,3,4-thiadiazine (CAS 62625-70-1) in rats:\n\n1. Absorption: No specific information on absorption was found for this compound in rats.\n\n2. Distribution: No specific information on distribution was found for this compound in rats.\n\n3. Metabolism: No specific information on metabolism was found for this compound in rats.\n\n4. Excretion: No specific information on excretion was found for this compound in rats.\n\nIt's important to note that the resources provided do not contain specific toxicokinetic information for 6-Methyl-2,5-diphenyl-6H-1,3,4-thiadiazine in rats. The available information is mostly about related compounds or general toxicokinetic principles. To obtain accurate toxicokinetic parameters for this specific compound, further experimental studies would be necessary.",
  'searched_keyphrases': ['Toxicokinetic parameters',
   '6-Methyl-2,5-diphenyl-6H-1,3,4-thiadiazine',
   'CAS number 62625-70-1',
   'synonyms of 6-Methyl-2,5-diphenyl-6H-1,3,4-thiadiazine',
   'rat toxicokinetics',
   'thiadiazine compounds',
   'pharmacokinetics in rats',
   'absorption of 6-Methyl-2,5-diphenyl-6H-1,3,4-thiadiazine',
   'distribution of 6-Methyl-2,5-diphenyl-6H-1,3,4-thiadiazine',
   'metabolism and excretion in rats'],
  'steps_taken': ['analyze_query', 'gather_context', 'query_with_context'],
  'results': {}}}